name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --build
