name: Run tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - $default-branch
  workflow_call:

jobs:
  test:
    name: Test, lint, format check
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
          - 3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Format
        run: >
          poetry run yapf -dr
          aws_secrets_cache
          tests

      - name: Run tests
        run: poetry run pytest tests
